Stat svc
MityaDD/java-explore-with-me pull request #3
Opened 2023-07-11 13:26 UTC by MityaDD

2023-07-12 19:01 UTC, Fleaman777 requested changes

2023-07-12 19:01 UTC, Fleaman777 commented on docker-compose.yml
> +      - STATS_SERVER_URL=http://server:9090
сейчас получается, что значения этой переменной окружения, используются то, которое указано в application.properties, а не то, которые в docker-compose, 
т.к. в application.propertie она никак не упоминается

2023-07-12 19:15 UTC, MityaDD commented on ewm-service/pom.xml
> +            <version>1.7.0</version>
сделал

2023-07-12 19:17 UTC, MityaDD commented on statistics-service/server/src/main/java/ru/practicum/controller/Controller.java
> +public class Controller {
переименовал в StatisticsController

2023-07-12 19:23 UTC, MityaDD commented on statistics-service/server/src/main/java/ru/practicum/controller/Controller.java
> +    public List<HitDTO> getHit(@RequestParam(name = "start") @DateTimeFormat(pattern = PATTERN) LocalDateTime start,
исправил

2023-07-12 19:40 UTC, MityaDD commented on docker-compose.yml
> +      - STATS_SERVER_URL=http://server:9090
исправил

2023-07-12 19:53 UTC, MityaDD commented on ewm-service/pom.xml
> +            <version>1.7.0</version>
конкретно если убрать <version>1.7.0</version> пишет
Could not find artifact org.springdoc: springdoc-openapi-vi:jar:unknown in central (https://repo.maven.apache.org/maven2)

2023-07-12 19:56 UTC, MityaDD commented
исправил согласно ревью

2023-07-13 15:42 UTC, Fleaman777 approved these changes

2023-07-13 16:31 UTC, merged