Main svc
MityaDD/java-explore-with-me pull request #4
Opened 2023-07-16 13:37 UTC by MityaDD

2023-07-17 19:17 UTC, Fleaman777 requested changes

2023-07-17 19:17 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        if (!event.getState().equals(EventState.PUBLISHED)) {
я бы тут отметил 2 момента 

1. eсли сравнивать enum или String через equals, то лучше это делать наоборот 
EventState.PUBLISHED.equals(event.getState()) так, если вдруг не будет значения event.getState() и оно будет равно null, то у нас приложение не закончится с NPE 

2. енамы лучше сравнивать через == так и работает быстрее, и выглядит по другому

2023-07-17 19:17 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
event.getConfirmedRequests() и event.getParticipantLimit() можно было бы вынести в отдельные локалькые переменные

2023-07-17 19:17 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/compilation/dto/Validated.java
> +}
Эти интерфейсы, как я понимаю, служат в качестве маркеров, чтобы указать, что классы, реализующие эти интерфейсы, могут быть созданы или обновлены, верно? 
Но на самом деле, эти маркерные интерфейсы не передают много информации, потому что они не требуют от реализующего класса определения каких-либо конкретных методов. Классы могут реализовывать эти интерфейсы без каких-либо действительных обязательств, что может привести к путанице.

Вместо использования маркерных интерфейсов, мы могли бы использовать аннотации. Аннотации в Java предоставляют более гибкий и мощный способ предоставления метаданных о наших классах.

Так выглядел бы этот подход:

public @interface Validated {
    public enum Mode {
        CREATE,
        UPDATE
    }
    
    Mode value();
}

@Validated(Mode.CREATE)
public class SomeEntity {
....
}

2023-07-17 19:17 UTC, Fleaman777 commented on docker-compose.yml
> +      - EWM_SERVICE_URL=http://server:8080
сейчас получается, что значения переменных окружения EWM_SERVICE_URL, STATS_SERVER_URL не используются, т.к. в application.properties они не проставлены

2023-07-17 20:33 UTC, MityaDD commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        log.info("Обновлена категория с id=" + catId);
Исправлено по всем классам сервисов

2023-07-17 20:51 UTC, MityaDD commented on ewm-service/src/main/java/ru/practicum/event/model/Event.java
> +    @Column(name = "description")
Я помню про этот момент по прошлому ревью. Разрываюсь между эстетикой целостной картинки, когда каждое поле одинаково аннотировано, и правильным стилем))
Исправил по всем энтити.

2023-07-17 21:23 UTC, MityaDD commented on docker-compose.yml
> +      - EWM_SERVICE_URL=http://server:8080
Исправил

2023-07-17 21:46 UTC, MityaDD commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        if (!event.getState().equals(EventState.PUBLISHED)) {
Исправил по всему проекту

2023-07-18 00:00 UTC, MityaDD commented
Исправлено согласно ревью

2023-07-18 19:52 UTC, Fleaman777 approved these changes

2023-07-18 19:52 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/compilation/dto/Validated.java
> +}
да, без проблем, 
твой подход тоже хорший)

2023-07-18 19:52 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        log.info("Запрошен список подборок еветов с параметром pinned={}", pinned);
евентов

2023-07-19 01:26 UTC, merged